### ISSUE TITLE
Support EdDSA in pubKeyCredParams

### ISSUE THREAD

**Issue by cnt0** [google/virtual-authenticators-tab#5]
Hello. I'm trying to create some credentials using the following code (please ignore the domain):
```js
        const options = {
          rp: {
              name: "Example CORP",
              id: "xxx.com",
              icon: "https://xxx.com/login.ico"
          },
          challenge: new Uint8Array(26), 
          user: {
              id: new Uint8Array(16),
              name: "john.p.smith@xxx.com",
              displayName: "John P. Smith",
          },
          pubKeyCredParams: [{
              type: "public-key",
              alg: -7,
          }],
          timeout: 1000,
          attestation: "none",
          extensions: {
            uvm: true,
            exts: true
          },
          authenticatorSelection:{
            authenticatorAttachment: "cross-platform",
            requireResidentKey: true,
            userVerification: "preferred"
          }
      }
      return navigator.credentials.create({  "publicKey": options })
```
Success. However, after changing `alg` to `-8`, it shows a timeout error (or just hangs if timeout is long enough).
So, can you please add -8 (EdDSA) to the list of supported algorithms? From [webauthn spec](https://www.w3.org/TR/webauthn-2):
>User agents MUST be able to return a non-null value for getPublicKey() when the credential public key has a COSEAlgorithmIdentifier value of:
> 
>-7 (ES256), where kty is 2 (with uncompressed points) and crv is 1 (P-256).
> 
>-257 (RS256).
> 
>-8 (EdDSA), where crv is 6 (Ed25519).

**Comment by nsatragno** [comment]
Thank you for your report! 

This should be supported for ctap2 authenticators on recent versions of chrome. Try creating a ctap2 authenticator on chrome >= 84  and see if you can repro.

**Comment by cnt0** [comment]
I upgraded my chromium to 85 & it works now. My previous chromium version was 84, so I likely messed something up yesterday. Anyway, thanks for extension
