### ISSUE TITLE
chromium crashes when trying to use the EdDSA key

### ISSUE THREAD

**Issue by cnt0** [google/virtual-authenticators-tab#6]
steps to reproduce:
- Chromium 85.0.4183.83 Arch Linux, this extension is installed from the chrome web store
- open https://webauthn.io (its sources are available [here](https://github.com/duo-labs/webauthn.io))
- create a virtual authenticator with default parameters
- force the website to use the EdDSA key. To do this, set the breakpoint before `navigator.credentials.create` call in [this](https://github.com/duo-labs/webauthn.io/blob/67203c5c36a79d215cc3427d62432a6a5adf126b/static/dist/js/webauthn.js#L112) line, press the `Register` button in the website interface, then, after reaching the breakpoint, run
```js
makeCredentialOptions.publicKey.pubKeyCredParams = [makeCredentialOptions.publicKey.pubKeyCredParams[9]]
```
and resume execution
- extension shows that the credential is successfully created
- press the `Login` button. Chromium crashes with message
```
'chromium' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
:((

**Comment by nsatragno** [comment]
Thank you for your bug report! ^_^

This is an issue in chromium. I have filed https://crbug.com/1123649 to track it, feel free to star it and CC yourself there to get updates.

Closing this issue since it's not a problem with the extension itself.

**Comment by nsatragno** [comment]
By the way, this bug should be fixed in the latest canary. Please give it a try!
